version: "3"

networks:
  grafana:
  loki:
  monitoring:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/:/var/log/
      - ./promtail/2promtail.yml:/etc/promtail/2promtail.yaml
    command:
      - "--config.file=/etc/promtail/2promtail.yaml"
    networks:
      - loki

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki

  node:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    networks:
      - grafana

  alertmanager:
    image: prom/alertmanager:latest
    networks:
      - grafana
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9094:9094"
    volumes:
      - ./alertmanager:/alertmanager
